document.writeln("<style>");
document.writeln("#zzwd{border:1px solid #c9c9c9; border-radius: 4px 4px;padding-top:5%;font-family:\"Microsoft YaHei\";  }");
document.writeln(".time{display:block;width:30%;text-align:center;line-height:0.15rem;font-size:0.09rem;color:#fff;margin:0 auto 3%;  background-color: #b4b4b4;-khtml-border-radius: 10px;-rim-border-radius: 10px;-ms-border-radius: 10px;-o-border-radius: 10px;-moz-border-radius: 10px;-webkit-border-radius: 10px;border-radius: 10px;}");
document.writeln("@media screen and (min-width:320px){.time{font-size:0.15rem; line-height:0.25rem; width:40%;}}");
document.writeln("@media screen and (min-width:360px){.time{font-size:0.15rem; line-height:0.25rem; width:40%;}}");
document.writeln("@media screen and (min-width:400px){.time{font-size:0.15rem; line-height:0.25rem; width:40%;}}");
document.writeln("@media screen and (min-width:440px){.time{font-size:0.15rem; line-height:0.25rem; width:40%;}}");
document.writeln("@media screen and (min-width:480px){.time{font-size:0.09rem; line-height:0.15rem; width:30%;}}");
document.writeln(".zzwdBoxItem{padding:0 5%; overflow: hidden;}");
document.writeln(".zzwdBoxItem img{display:block;width:20%;float:left;margin-right:3%;}");
document.writeln(".message1{width:67%;background:url(images/mesBg.png) no-repeat;float:left;line-height:0.15rem;padding-left:4%;padding-right:3%;color:#222; -moz-background-size:100% 100%;");
document.writeln("    -webkit-background-size:100% 100%;");
document.writeln("    -o-background-size:100% 100%;");
document.writeln("    background-size:100% 100%;line-height: 24px;}");
document.writeln(".message1 p {  padding: 5%;text-indent: 0em;line-height: 0.15rem; font-size:0.09rem; color:#fff;margin-top: 3%;margin-left: 0%;}");
document.writeln("@media screen and (min-width:320px){.message1 p{font-size:0.15rem; line-height: 0.25rem;}}");
document.writeln("@media screen and (min-width:360px){.message1 p{font-size:0.15rem; line-height: 0.25rem;}}");
document.writeln("@media screen and (min-width:400px){.message1 p{font-size:0.15rem; line-height: 0.25rem;}}");
document.writeln("@media screen and (min-width:440px){.message1 p{font-size:0.15rem; line-height: 0.25rem;}}");
document.writeln("@media screen and (min-width:480px){.message1 p{font-size:0.09rem; line-height: 0.15rem;}}");
document.writeln(".message1 p a {color:black;font-size:14px}");
document.writeln("#footbar {background-color:#ffffff;width: 100%;padding-top:15px;padding-bottom:65px; font-size:18px}");
document.writeln("#address {width: 100%;	margin:0 auto 10px;	font-family:\"微软雅黑\";	font-size:16px;	color:#5F5F60;	font-weight:bold;text-align:center;}");
document.writeln("#address p{line-height:26px;}");
document.writeln("#tab4{	margin-bottom:10px;	}");
document.writeln("#tab4 ul{ height:49px;}");
document.writeln("#tab4 li{ float:left; display:inline; width:50%; height:49px; text-align:center;}");
document.writeln("");
document.writeln("<\/style>");
document.writeln("<div id=\"zzwd\">");
document.writeln("<div class=\"zzwdBox\">");
document.writeln("<span class=\"time\"><script type=\"text\/javascript\">");
document.writeln("var week;");
document.writeln("if(new Date().getDay()==0)          week=\"星期日\"");
document.writeln("if(new Date().getDay()==1)          week=\"星期一\"");
document.writeln("if(new Date().getDay()==2)          week=\"星期二\"");
document.writeln("if(new Date().getDay()==3)          week=\"星期三\"");
document.writeln("if(new Date().getDay()==4)          week=\"星期四\"");
document.writeln("if(new Date().getDay()==5)          week=\"星期五\"");
document.writeln("if(new Date().getDay()==6)          week=\"星期六\"");
document.writeln("");
document.writeln("var myDate = new Date();");
document.writeln("shijian = myDate.getHours()+\":\"+myDate.getMinutes(); ");
document.writeln("document.write(week+\"　\"+shijian);");
document.writeln("");
document.writeln("<\/script><\/span>");
document.writeln("<div class=\"zzwdBoxItem\">");
document.writeln("<img alt=\"\" src=\"\images\/expertPic.jpg\">");
document.writeln("<div class=\"message1\">");
document.writeln("<a href=\"\#\"><p>您好，请问您有哪些问题要咨询，请讲？<\/p><\/a>");
document.writeln("<\/div>");
document.writeln("<div class=\"clear\"><\/div>");
document.writeln("<\/div>");
document.writeln("<div class=\"zzwdBox_swt\"><a href=\"\#\"><img src=\"\images\/dibu_swt.gif\" style=\"width:100%;\"><\/a><\/div>");
document.writeln("<\/div>");
document.writeln("");
document.writeln("<\/div>");